version: '3.7'

services:
  netcom-web:
    build: ./backend
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8002:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@netcom-db:5432/netcom_dev
      - AUTH_SECRET_KEY=740e812e52f29efb13c903ec80951fa2616155ad8d80ce644537aee284398538
      - DATABASE_TEST_URL=postgres://postgres:postgres@netcom-db:5432/netcom_test
      - AUTH_TOKEN_EXPIRY_MINUTES=5
      - SMTP_HOST=
      - SMTP_PORT=
      - SMTP_TLS=
      - SMTP_USER=
      - SMTP_PASSWORD=
      - EMAILS_FROM_NAME=
      - EMAILS_FROM_EMAIL=
    depends_on:
      - netcom-db

  netcom-db:
    build:
      context: ./backend/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres